apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-end-dbaz
  labels:
    app: back-end-dbaz
spec:
  replicas: 1
  selector:
    matchLabels:
      app: back-end-dbaz
  template:
    metadata:
      labels:
        app: back-end-dbaz
    spec:
      containers:
      - name: back-end-dbaz
        image: cirros
        ports:
        - containerPort: 123
      nodeSelector:
        location: az

