apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-end-1
  labels:
    app: back-end-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: back-end-1
  template:
    metadata:
      labels:
        app: back-end-1
    spec:
      containers:
      - name: back-end-1
        image: cirros
        ports:
        - containerPort: 223
      nodeSelector:
        location: dc2

